services:
  server_app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - imgsrc:/app/src/public
    env_file:
      - .env
    command: sh -c "npm start"
    restart: unless-stopped

volumes:
  imgsrc:
